#!/usr/bin/env bash
# codex.sh {install|uninstall|status} [--dry-run] [--settings PATH]
set -euo pipefail

SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -P "$SCRIPT_DIR/../.." && pwd)"
TX="$REPO_ROOT/bin/tx"
# The installer seams (`tx _…`) take every path as a flag. Run them against a throwaway
# TX_IDE_HOME: like every verb, `tx` creates its home skeleton on start, and an uninstall / status /
# dry run must not grow one.
tx_seam() {
  local scratch rc=0
  scratch="$(mktemp -d)"
  TX_IDE_HOME="$scratch" "$TX" "$@" || rc=$?
  rm -rf "$scratch"
  return "$rc"
}

# Expand a leading ~ by hand — env vars are not tilde-expanded.
TX_HOME="${TX_IDE_HOME:-$HOME/.tx-ide}"
TX_HOME="${TX_HOME/#\~/$HOME}"

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CODEX_HOME="${CODEX_HOME/#\~/$HOME}"
LIVE_CODEX_HOME="$HOME/.codex"

STAMP="$(date +%Y%m%d%H%M%S)"

B=$'\e[1m'; G=$'\e[32m'; Y=$'\e[33m'; RED=$'\e[31m'; D=$'\e[2m'; X=$'\e[0m'
ok()     { printf '  %s→%s %-46s %s%s%s\n' "$G" "$X" "$1" "$G" "${2:-ok}" "$X"; }
warn()   { printf '  %s→%s %-46s %s%s%s\n' "$Y" "$X" "$1" "$Y" "${2:-}" "$X"; }
info()   { printf '  %s%s%s\n' "$D" "$*" "$X"; }
header() { printf '\n%s%s%s\n' "$B" "$*" "$X"; }
die()    { printf '%scodex.sh: %s%s\n' "$RED" "$*" "$X" >&2; exit 1; }

usage() {
  cat >&2 <<EOF
usage: codex.sh {install|uninstall|status} [--dry-run] [--settings PATH]

  install     write tx-ide's Codex hooks (hooks.json + shims) + the marked config.toml [tui] block
  uninstall   reverse it exactly — strip the config.toml block, remove our hooks.json + shims
  status      report what is installed vs. what hooks.json / config.toml hold

  --dry-run        print every action, change nothing
  --settings PATH  edit PATH (a config.toml copy) — sandbox: requires a throwaway CODEX_HOME
EOF
}

OP=""; DRY_RUN=0; SETTINGS=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    install|uninstall|status) OP="$1"; shift ;;
    --dry-run)        DRY_RUN=1; shift ;;
    --settings)       SETTINGS="${2:?--settings needs a PATH}"; shift 2 ;;
    --settings=*)     SETTINGS="${1#*=}"; shift ;;
    -h|--help)        usage; exit 0 ;;
    *) printf 'codex.sh: unknown argument: %s\n' "$1" >&2; usage; exit 2 ;;
  esac
done
[[ -n "$OP" ]] || { usage; exit 2; }

# --settings ⇒ sandbox: hooks.json is keyed off CODEX_HOME (not --settings), so refuse a live
# CODEX_HOME here or a sandbox run would leak into the real ~/.codex.
SANDBOX=0
if [[ -n "$SETTINGS" ]]; then
  SANDBOX=1
  CONFIG_TOML="$SETTINGS"
  if [[ "$CODEX_HOME" == "$LIVE_CODEX_HOME" ]]; then
    die "--settings (sandbox) requires a throwaway CODEX_HOME (e.g. CODEX_HOME=\$(mktemp -d)) — refusing to write the live ~/.codex/hooks.json"
  fi
else
  CONFIG_TOML="$CODEX_HOME/config.toml"
fi
HOOKS_JSON="$CODEX_HOME/hooks.json"

# Codex events fan in to these shims via hooks.json. No notify/end shims — Codex has no
# Notification / SessionEnd event.
START_SHIM="$TX_HOME/hooks/codex/start.sh"  # SessionStart                                                  → session-start
PRE_SHIM="$TX_HOME/hooks/codex/pre.sh"      # UserPromptSubmit                                              → prompt-submit
WORK_SHIM="$TX_HOME/hooks/codex/work.sh"    # PreToolUse/PostToolUse/PreCompact/PostCompact/SubagentStart   → working
POST_SHIM="$TX_HOME/hooks/codex/post.sh"    # Stop / PermissionRequest                                      → stop

write_shim() {  # <path> <subcommand>
  local path="$1" subcommand="$2"
  if [[ $DRY_RUN -eq 1 ]]; then
    info "would generate shim $path  ($subcommand --engine codex, home baked = $TX_HOME)"
    return 0
  fi
  mkdir -p "$(dirname "$path")"
  cat >"$path" <<EOF
#!/bin/bash
# tx-ide Codex hook shim — GENERATED by setup/engines/codex.sh. Do NOT edit; re-run the installer to
# regenerate. \$TX_IDE_HOME and the tx binary are baked in as literals because Codex runs hooks with
# a minimal env. stdin is left CONNECTED so \`tx hook\` can read session_id/transcript_path off the
# JSON payload (the universal capture path); --engine codex selects the Codex adapter.
exec env TX_IDE_HOME="$TX_HOME" "$TX" hook $subcommand --engine codex
EOF
  chmod +x "$path"
  ok "shim $path" "$subcommand"
}

remove_shim() {  # <path>
  local path="$1"
  if [[ $DRY_RUN -eq 1 ]]; then info "would remove shim $path"; return 0; fi
  if [[ -f "$path" ]]; then rm -f "$path"; ok "removed $path"; else info "$path (already absent)"; fi
}

# The tx-owned hooks.json (each Codex event → its shim; the whole file is tx's, so install writes it
# wholesale and uninstall removes it only while it is still byte-for-byte ours) + the marked
# config.toml [tui] block (status_line is a fixed segment enum, not a scriptable command).
run_codex() {  # <install|uninstall|status>
  local -a args=("$1" "--hooks-json=$HOOKS_JSON" "--config-toml=$CONFIG_TOML"
                 "--update-log=$TX_HOME/codex-update/update.log" "--home=$TX_HOME" "--stamp=$STAMP")
  [[ $DRY_RUN -eq 1 ]] && args+=(--dry-run)
  tx_seam _codex-hooks "${args[@]}"
}

cmd_install() {
  printf '%s== codex.sh install ==%s  %s\n' "$B" "$X" "$( ((DRY_RUN)) && echo '(dry-run)'; ((SANDBOX)) && echo "(sandbox: $CONFIG_TOML)")"
  header "Codex hook shims under $TX_HOME/hooks/codex (stdin kept, --engine codex)"
  write_shim "$START_SHIM" session-start
  write_shim "$PRE_SHIM"   prompt-submit
  write_shim "$WORK_SHIM"  working
  write_shim "$POST_SHIM"  stop

  header "tx-owned hooks.json + marked config.toml [tui] block (no trust hash — bypass-first)"
  run_codex install
}

cmd_uninstall() {
  printf '%s== codex.sh uninstall ==%s  %s\n' "$B" "$X" "$( ((DRY_RUN)) && echo '(dry-run)'; ((SANDBOX)) && echo "(sandbox: $CONFIG_TOML)")"
  header "Reverse the marked config.toml [tui] block + the tx-owned hooks.json"
  run_codex uninstall

  header "Remove generated Codex hook shims"
  remove_shim "$START_SHIM"
  remove_shim "$PRE_SHIM"
  remove_shim "$WORK_SHIM"
  remove_shim "$POST_SHIM"
}

cmd_status() {
  printf '%s== codex.sh status ==%s  %sCODEX_HOME=%s%s\n' "$B" "$X" "$D" "$CODEX_HOME" "$X"
  header "Codex integration"
  run_codex status
  header "Generated shims ($TX_HOME/hooks/codex)"
  for shim in "$START_SHIM" "$PRE_SHIM" "$WORK_SHIM" "$POST_SHIM"; do
    if [[ -f "$shim" ]]; then ok "$shim" "present"; else warn "$shim" "missing"; fi
  done
}

case "$OP" in
  install)   cmd_install ;;
  uninstall) cmd_uninstall ;;
  status)    cmd_status ;;
esac
